base:
  logger_path: "/tmp/zyrl/logs"
  reward_threshold: "none"
  mode: "low_level"

net:
  type: "mlp"
  hidden_sizes: [128, 128]

algo:
  lr: 0.001

trainer:
  buffer_size: 20000
  train_num: 10
  test_num: 10
  max_epoch: 10
  step_per_epoch: 10000
  step_per_collect: 5
  batch_size: 256
  update_per_step: 0.2
